
name: nightly_build

on:
  # push:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # 5 am UTC (11pm MDT the day before) every weekday night in MDT
    - cron: '21 5 * * 2-6'

# Cancels an existing job (of the same workflow) if it is still running
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

env:
  # This env var should enforce develop branch of all dependencies
  FAVOR_LOCAL_GEMS: true
  GEM_DEVELOPER_KEY: ${{ secrets.GEM_DEVELOPER_KEY }}

jobs:
  weeknight-tests:
    # ubuntu-latest works since https://github.com/rbenv/ruby-build/releases/tag/v20220710 (July 10, 2022)
    # https://github.com/rbenv/ruby-build/discussions/1940
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.5.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update gems
        run: |
          bundle update
      - name: Run Rspec
        run: bundle exec rspec
      # coveralls action docs: https://github.com/marketplace/actions/coveralls-github-action
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov/urbanopt-geojson-gem.lcov"
